
-- --------------------------------------------------------

--
-- Estrutura da tabela `catalogue_pages`
--

CREATE TABLE `catalogue_pages` (
  `id` int(11) NOT NULL,
  `order_id` int(11) DEFAULT NULL,
  `min_role` int(11) DEFAULT NULL,
  `index_visible` tinyint(1) NOT NULL DEFAULT '1',
  `is_club_only` tinyint(1) NOT NULL DEFAULT '0',
  `name_index` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link_list` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `layout` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_headline` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_teasers` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8mb4_unicode_ci,
  `label_pick` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label_extra_s` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label_extra_t` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Extraindo dados da tabela `catalogue_pages`
--

INSERT INTO `catalogue_pages` (`id`, `order_id`, `min_role`, `index_visible`, `is_club_only`, `name_index`, `link_list`, `name`, `layout`, `image_headline`, `image_teasers`, `body`, `label_pick`, `label_extra_s`, `label_extra_t`) VALUES
(1, 1, 1, 1, 0, 'Frontpage', '', 'Frontpage', 'ctlg_frontpage2', 'catal_fp_header', 'catal_fp_pic4,catal_fp_pic5,', 'Welcome to the Hotel Catalogue. It\'s packed full of fab things for your room - there\'s something for everyone! Browse the ranges by clicking the tabs on the right.<br><br>Some ranges are seasonal, so check back regularly for new items.<br><br>We regularly', NULL, 'Home sweet home!', '1:You need Credits to buy Furni for your room, click the Purse at the bottom of your screen for more information about Credits.'),
(2, 2, 1, 1, 0, 'Rare', '', 'Rare', 'ctlg_productpage1', 'catalog_rares_headline1', '', 'Okay this thing is fucking epic!\rEnjoy it while it lasts!', NULL, NULL, NULL),
(3, 3, 1, 1, 0, 'Spaces', '', 'Spaces', 'ctlg_spaces', 'catalog_spaces_headline1', '', 'Floors, wallpapers, landscapes - get a groovy combination to your room. Use our virtual room preview below to test out the combinations before you buy. Select the design and color you like and click Buy.', NULL, NULL, '1:Wall\r\n2:Floor\r\n3:Pattern\r\n4:Colour\r\n5:Pattern\r\n6:Colour\r\n7:Preview'),
(4, 27, 1, 1, 0, 'Habbo Exchange', '', 'Habbo Exchange', 'ctlg_layout2', 'catalog_bank_headline1', 'catalog_bank_teaser,', 'The Habbo Exchange is where you can convert your Habbo Credits into a tradable currency. You can use this tradable currency to exchange Habbo Credits for Furni!', 'Click on the item you want for more information', '1:Refundable      goods!', NULL),
(5, 22, 1, 1, 0, 'Rollers', '', 'Rollers', 'ctlg_layout2', 'catalog_roller_headline1', 'catalog_roller_teaser1', 'Move your imagination, while you move your Habbo!  Perfect for mazes, games, for keeping your queue moving or making your pet go round in circles for hours.  Available in multi-packs ? the more you buy the cheaper the Roller! Pink Rollers out now!', 'Click on a Roller to see more information!', 'You can fit 30 Rollers in a user flat!', NULL),
(6, 6, 1, 1, 0, 'Teleporters', '', 'Teleporters', 'ctlg_productpage3', 'catalog_doors_headline1', 'catalog_door_a,catalog_door_c,catalog_door_b,', 'Beam your user from one room to another with one of our cunningly disguised, space age teleports. Now you can link any two rooms together! Teleports are sold in pairs, so if you trade for them, check you\'re getting a linked pair.', 'Click on the item you want for more information', 'Beam!', NULL),
(7, 18, 1, 1, 0, 'Pets', '', 'Pets', 'ctlg_pets', 'catalog_pet_headline1', 'catalog_pets_teaser1,', 'Fluff and whiskers, meows and woofs! You\'\'re about to enter the world of small creatures with furry features. Find a new friend from our ever-changing selection. From faithful servants to playful playmates - here\'s where you\'\'ll find them all.', 'Find your own pet!', NULL, '1:Give name:'),
(8, 19, 1, 1, 0, 'Pet Accessories', '', 'Pet Accessories', 'ctlg_layout2', 'catalog_pet_headline2', 'ctlg_pet_teaser1,', 'You\'\'ll need to take care of your pet to keep it happy and healthy. This section of the Catalogue has EVERYTHING you\'ll need to satisfy your pet\'s needs.', 'Click on the item you want for more information', '2:You\'ll have to share it!', NULL),
(9, 6, 1, 1, 0, 'Area', '', 'Area', 'ctlg_layout2', 'catalog_area_headline1', 'catalog_area_teaser1,', 'Introducing the Area Collection...  Clean, chunky lines set this collection apart as a preserve of the down-to-earth person. It\'s beautiful in its simplicity, and welcoming to everyone.', 'Click on the item you want for more information', '2: Beautiful in it\'s simplicity!', NULL),
(10, 10, 1, 1, 0, 'Gothic', '', 'Gothic', 'ctlg_layout2', 'catalog_gothic_headline1', 'catalog_gothic_teaser1,', 'The Gothic section is full of medieval looking items. Create your own Gothic castle!', 'Click on the item you want for more information', NULL, NULL),
(11, 11, 1, 0, 0, 'Soundmachines', '', 'Trax', 'ctlg_soundmachine', 'catalog_djshop_headline1', 'catalog_djshop_teaser1,', 'Bring sound to your room! Purchase a sound machine plus some sample packs and create your own songs to play in your flat!', 'Click on the item you want for more information', NULL, NULL),
(12, 7, 1, 1, 0, 'Candy', '', 'Candy', 'ctlg_layout2', 'catalog_candy_headline1', 'catalog_candy_teaser1,', 'Candy combines the cool, clean lines of the Mode collection with a softer, more soothing style. It\'\'s urban sharpness with a hint of the feminine.', 'Click on the item you want for more information', '2: Relax! It\'s faux-fur.', NULL),
(13, 13, 1, 1, 0, 'Asian', '', 'Asian', 'ctlg_layout2', 'catalog_asian_headline1', 'catalog_asian_teaser1,', 'Introducing the Asian collection... These handcrafted items are the result of years of child slavery, some mixture of Ying and Yang and a mass-shipping from China. These authentic items fit in every oriental themed user flat. Made in China: fo\' real nigga', 'Click on the item you want for more information', NULL, NULL),
(14, 9, 1, 1, 0, 'Iced', '', 'Iced', 'ctlg_layout2', 'catalog_iced_headline1', 'catalog_iced_teaser1,', 'Introducing the Iced Collection...  For the person who needs no introduction. It\'s so chic, it says everything and nothing. It\'s a blank canvas, let your imagination to run wild!', 'Click on the item you want for more information', '2: These chairs are so comfy.', NULL),
(15, 10, 1, 1, 0, 'Lodge', '', 'Lodge', 'ctlg_layout2', 'catalog_lodge_headline1', 'catalog_lodge_teaser1,', 'Introducing the Lodge Collection...  Do you appreciate the beauty of wood?  For that ski lodge effect, or to match that open fire... Lodge is the Furni of choice for people with that no frills approach to decorating.', 'Click on the item you want for more information', '2: I LOVE this wood Furni!', NULL),
(16, 12, 1, 1, 0, 'Plastic', '', 'Plasto', 'ctlg_plasto', 'catalog_plasto_headline1', '', 'Introducing The Plasto Collection...  Can you feel that 1970s vibe?  Decorate with Plasto and add some colour to your life. Choose a colour that reflect your mood, or just pick your favourite shade.', 'Select an item and a colour and buy!', 'New colors!', '1:Choose an item\r\n2:Select the color\r\n3:Preview'),
(17, 13, 1, 1, 0, 'Pura', '', 'Pura', 'ctlg_layout2', 'catalog_pura_headline1', 'catalog_pura_teaser1,', 'Introducing the Pura Collection...  This collection breathes fresh, clean air and cool tranquillity. Use it to create a special haven away from the hullabaloo of life outside the Hotel.', 'Click on the item you want for more information', NULL, NULL),
(18, 11, 1, 1, 0, 'Mode', '', 'Mode', 'ctlg_layout2', 'catalog_mode_headline1', 'catalog_mode_teaser1,', 'Introducing the Mode Collection...  Steely grey functionality combined with sleek designer upholstery. The person that chooses this furniture is a cool urban cat - streetwise, sassy and so slightly untouchable.', 'Click on the item you want for more information', '2: So shiny and new...', NULL),
(19, 24, 1, 1, 0, 'Accessories', '', 'Accessories', 'ctlg_layout2', 'catalog_extra_headline1', 'catalog_extra_teaser1,', 'Is your room missing something?  Well, now you can add the finishing touches that express your true personality. And don\'t forget, like everything else, these accessories can be moved about to suit your mood.', 'Click on the item you want for more information', '2: I love my rabbit...', NULL),
(20, 15, 1, 1, 0, 'Bathroom', '', 'Bathroom', 'ctlg_layout2', 'catalog_bath_headline1', 'catalog_bath_teaser1,', 'Introducing the Bathroom Collection...  Have some fun with the cheerful bathroom collection. Give yourself and your guests somewhere to freshen up - vital if you want to avoid nasty niffs. Put your loo in a corner though...', 'Click on the item you want for more information', '2:  Every Habbo needs one!', NULL),
(21, 16, 1, 1, 0, 'Plants', '', 'Plants', 'ctlg_layout2', 'catalog_plants_headline1', 'catalog_plants_teaser1,', 'Introducing the Plant Collection...  Every room needs a plant! Not only do they bring a bit of the outside inside, they also enhance the air quality! Do we give a fuck? Up to you!', 'Click on the item you want for more information', NULL, NULL),
(22, 22, 1, 1, 0, 'Sports', '', 'Sport', 'ctlg_layout2', 'catalog_sports_headline1', 'catalog_sports_teaser1,', 'For the sporty people, here is the Sports section! Create your own hockey stadium!', 'Click on the item you want for more information', '', NULL),
(23, 17, 1, 1, 0, 'Rugs', '', 'Rugs', 'ctlg_layout2', 'catalog_rugs_headline1', 'catalog_rugs_teaser1,', 'We have rugs for all occasions. All rugs are non-slip and washable.', 'Click on the item you want for more information', '2:We have rugs for ANY room!', NULL),
(24, 25, 1, 1, 0, 'Gallery', '', 'Gallery', 'ctlg_layout2', 'catalog_gallery_headline1', 'catalog_posters_teaser1,', 'Adorn your walls with wondrous works of art, posters, plaques and wall hangings. We have items to suit all tastes, from kitsch to cool, traditional to modern.', 'Click on the item you want for more information', '2: Brighten up your walls!', NULL),
(25, 26, 1, 1, 0, 'Flags', '', 'Flags', 'ctlg_layout2', 'catalog_flags_headline1', 'catalog_flags_teaser1,', 'If you\'re feeling patriotic, get a flag to prove it. Our finest cloth flags will brighten up the dullest walls.', 'Click on the item you want for more information', '2:  Flag this     section for later!', NULL),
(26, 23, 1, 1, 0, 'Trophies', '', 'Trophies', 'ctlg_trophies', 'catalog_trophies_headline1', '', 'Reward your friends, or yourself with one of our fabulous glittering array of bronze, silver and gold trophies.<br><br>First choose the trophy model (click on the arrows to see all the different styles) and then the metal (click on the seal below the trop', NULL, NULL, '1:Type your inscription CAREFULLY, it\'s permanent!'),
(27, 108, 5, 1, 0, 'Club Gifts', '', 'Club Gifts', 'ctlg_layout2', 'catalog_club_headline1', 'catalog_hc_teaser,', 'Welcome to the Club Shop! All \'Habbo Club membership gifts\' are available here, use them wisely you greedy cunt! We have sofas, butlers and all the happy stuff.', 'Click on the item you want for more information', NULL, NULL),
(28, 110, 5, 1, 0, 'Dragons', '', 'Dragons', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser2', 'The Dragon page contains all of the Dragon Lamps.', 'Click on the item you want for more information', NULL, NULL),
(29, 111, 5, 1, 0, 'Sci-fi Doors', '', 'Sci-fi Doors', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(30, 112, 5, 1, 0, 'Parasols', '', 'Parasols', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(31, 113, 5, 1, 0, 'Screens', '', 'Screens', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser5', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(32, 100, 5, 1, 0, 'Marquee', '', 'Marquee', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser1', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(33, 101, 5, 1, 0, 'Pillows', '', 'Pillows', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(34, 102, 5, 1, 0, 'Icecream', '', 'Icecream', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(35, 103, 5, 1, 0, 'Smoke machines', '', 'Smoke machines', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(36, 104, 5, 1, 0, 'Laser Ports', '', 'Laser Ports', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(37, 105, 5, 1, 0, 'Amber Lamp', '', 'Amber Lamp', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(38, 106, 5, 1, 0, 'Fountains', '', 'Fountains', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(39, 107, 5, 1, 0, 'Elephants', '', 'Elephants', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(40, 109, 5, 1, 0, 'Fans', '', 'Fans', 'ctlg_layout2', 'catalog_rares_headline1', '', 'Yet another rares page.', 'Click on the item you want for more information', NULL, NULL),
(41, 20, 1, 1, 0, 'Camera', 'Camera2', 'Camera', 'ctlg_camera1', 'catalog_camera_headline1', 'campic_cam,campic_film,', 'With your Camera you can take pictures of just about anything in the hotel - your friend on the loo (hehe), your best dive in the Lido, or your room when you\'ve got it just right!<br><br>A camera costs 10 Credits (two free photos included).', NULL, NULL, '1:When you\'ve used your free photos, you\'ll need to buy more. Each roll of film takes five photos. Your Camera will show how much film you have left and loads the next roll automatically.<br><br>Each Film (5 photos) costs:'),
(42, 21, 1, 0, 0, 'Camera2', '', 'Camera', 'ctlg_camera2', 'catalog_camera_headline1', 'campic_help,', 'CAMERA FUNCTIONS<br><br>1. Press this button to take a photo.<br>2. Photo cancel - for when you\'ve chopped off your friend\'s head!<br>3. Zoom in and out.<br>4. Photo counter - shows how much film you have left<br>5. Caption Box - write your caption before saving the photo.<br>6. Save - this moves the photo to your giant.<br>You can give photos to your friends, or put them on the wall like posters.', NULL, NULL, NULL),
(43, 114, 5, 1, 0, 'Inflatable Chairs', '', 'Inflatable Chairs', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser6', 'Yet another rares page.', 'Click on the item you want for more information', '1: A summer miracle!', NULL),
(44, 116, 5, 1, 0, 'Rares Mixed', '', 'Rares Mixed', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser8', 'Yet another rares page.', 'Click on the item you want for more information', '1:Top Secret Content!', NULL),
(45, 27, 1, 1, 0, 'Executive', '', 'Executive', 'ctlg_layout2', 'catalog_exe_headline1', 'catalog_exe_teaser', 'The Executive Furni is ideal for creating a sophisticated working environment, whether it be an office, a mafia headquarters or study!', 'Click on the item you want for more information', '', ''),
(46, 28, 1, 1, 0, 'Alhambra', '', 'Alhambra', 'ctlg_layout2', 'catalog_alh_headline2', 'catalog_alh_teaser2,', 'The Palace of Alhambra has appeared and with it this exotic and beautifully crafted range of Arabian Furni. Luxury seating and gourmet food combine to make your room sparkle with riches.', 'Click on the item you want for more information', 's:2:Get your Alhambrian goodies now!', ''),
(60, 35, 1, 1, 0, 'Habbo Club', 'Club Info', 'Habbo Club', 'ctlg_club1', 'catalog_club_headline1', 'clubcat_pic', '', '', '', '1:Welcome to Habbo Club - the members only club that all the best Habbos belong to!\r\n2:Every member of Habbo Club gets priority access to the hotel. So, if the hotel\'s full up, you\'ll get to the front of the queue automatically - no waiting around! And you\'ll get exclusive clothes, hair colours, furni, special guest room layouts and more besides. Normal Habbos will not have any of these.\r\n3:How do I join? Use the Navigator to go to \'Hotel View\' and click on the Habbo Club icon. Habbo Club costs 20 Credits a month. We\'ll remind you when your membership is about to run out.\r\n4:Well, what are you waiting for? Join Habbo Club today!'),
(61, 5, 1, 0, 0, 'Club Info', '', 'Club Info', 'ctlg_club2', 'catalog_club_headline1', 'club_pos,club_neg', '', '', '', '1:What happens when my Habbo Club runs out?\r\n2:If your Habbo Club runs out, you WILL be able to keep any rooms you made with a Club layout and the Habbo Club Furni is yours to keep.\r\n3:If your Habbo Club runs out you WON\'T be able to wander around with a cool HC badge, the funky clothes and your hair will vanish from your Habbo, you won\'t be able to do chose HC rooms layouts in the Room-O-Matics, you\'ll receive no new HC Furni and worst all, you won\'t be able to jump the queue if the Hotel\'s Full!\r\n4:Stay in Habbo Club for more than a year and you\'ll get a special sparkly BADGE!'),
(64, 4, 1, 1, 1, 'Club Shop', '', 'Club Shop', 'ctlg_layout2', 'catalog_club_headline1', 'catalog_hc_teaser', 'NEW Habbo Club Furni range. Allow these elegant delights to make your room sophisticated and humble. They look great placed with your monthly gifts!', 'Click on the item you want for more information', '1:For Habbo Club members only!', ''),
(68, 14, 1, 1, 0, 'Romantique', '', 'Romantique', 'ctlg_layout2', 'catalog_romantique_headline1', 'catalog_romantique_teaser1', 'The Romantique range features Grand Pianos, old antique lamps and tables. It is the ideal range for setting a warm and loving mood in your room. Spruce up your room and invite that special someone over. Now featuring the extra special COLOUR edition.', 'Click on the item you want for more information', NULL, ''),
(81, 8, 1, 1, 0, 'Grunge', '', 'Grunge', 'ctlg_layout2', 'catalog_gru_headline1', 'catalog_gru_teaser', 'The Grunge range will get your bedroom looking just the way you like it - organised, neat and tidy!', 'Click on the item you want for more information', NULL, ''),
(84, 29, 1, 0, 0, 'How to make music?', '', 'How to make music?', 'ctlg_soundmachine', 'catalog_djshop_headline1', 'catalog_djshop_teaser1', 'You must own a trax machine and at least one trax pax. Place the trax machine in your room and the trax pax in your hand. Double click the trax machine, click \"Trax editor\" and start editing music. When ready, save, select the tune, turn on the trax machine and enjoy.', 'Cool, my own music!', NULL, ''),
(85, 28, 1, 1, 0, 'Ambient Trax', '', 'Ambient Trax', 'ctlg_soundmachine', 'catalog_trx_header1', 'catalog_trx_teaser1', 'Welcome to the Ambient Trax Store! With groovy beats and chilled out melodies, this is the section for some cool and relaxing tunes.', '', NULL, ''),
(86, 29, 1, 1, 0, 'Dance Trax', '', 'Dance Trax', 'ctlg_soundmachine', 'catalog_trx_header2', 'catalog_trx_teaser2', 'Welcome to the Dance Trax Store! With funky beats and catchy melodies, this is the section for every clubber  to indulge in.', '', NULL, ''),
(87, 30, 1, 1, 0, 'Rock Trax', '', 'Rock Trax', 'ctlg_soundmachine', 'catalog_trx_header3', 'catalog_trx_teaser3', 'Welcome to the Rock Trax Store! With heavy beats and rockin\' riffs, this is the section for every rock fan to experiment with.', '', NULL, ''),
(88, 31, 1, 1, 0, 'SFX Trax', '', 'SFX Trax', 'ctlg_soundmachine', 'catalog_trx_header4', 'catalog_trx_teaser4', 'Welcome to the SFX Trax Store! With crazy sounds and weird noises, this is the section for every creative room builder  to indulge in.', '', NULL, ''),
(89, 32, 1, 1, 0, 'Urban Trax', '', 'Urban Trax', 'ctlg_soundmachine', 'catalog_trx_header5', 'catalog_trx_teaser5', 'Welcome to the Urban Trax Store! With hip hop beats and RnB vocals, this is the section for every city bopper  to indulge in.', '', NULL, ''),
(90, 34, 1, 1, 0, 'Presents', '', 'Presents', 'ctlg_presents', 'catalog_gifts_headline1', 'catalog_presents_teaser1,catalog_presents_teaser2', 'Show your Habbo friends just how much you care and send them a gift from the Habbo Catalogue.  ANY Catalogue item can be sent as a gift to ANY Habbo, all you need is their Habbo name!', '', NULL, '1:Buying an item as a gift couldn\'t be simpler...  <br><br>Buy an item from the Catalogue in the normal way, but tick \'buy as a gift\'. Tell us which Habbo you want to give the gift to and we\'\'ll gift wrap it and deliver it straight to their hand.'),
(91, 115, 5, 1, 0, 'Sun Lounges', '', 'Sun Lounges', 'ctlg_layout2', 'catalog_rares_headline1', 'catalog_rares_teaser7', 'Exclusive RetroCMS Rares Content, credits to m.tiago04 and Alito from Ragezone.', 'Click on the item you want for more information', '2: Okay, who\'s ready for a break ?', '');
